# LU Factorization

<h3 style="color: blue">Introduction</h3>

The goal of LU Factorization is to solve the system of equations $Ax = b$, where $A$ is an $nxn$ matrix and $b$ is a vector of dimension $n$. The idea of LU Factorization is to transform the matrix $A$ into an $nxn$ upper-triangular matrix $U$ by introducing zeros below the diagonal. This is done by subtracting multiples of each row from subsequent rows. This "elimination" process is equivalent to multiplying A by a sequence of lower-triangular matrices $L_k$ on the left:

$$ L_{m-1}L_{m-2}\dots L_2L_1A = U $$

Setting $L = L_{m-1}^{-1}L_{m-2}^{-1}\dots L_2^{-1}L_1^{-1}$, we get: 

$$A = LU$$ 

Thus we obtain an LU factorization of $A$. where the matrix $U$ is upper-triangular and the matrix $L$ is lower-triangular. In practical Gaussian elimination, the matrices $L_k$ are never formed and multiplied explicitly since the elements of the matrix L are just the value of $l_{jk}$, where 

$$l_{jk} = \frac{a_{jk}}{a_{kk}}$$


In [1]:
# TAlgorithm - Gaussian Elimination without Pivoting
import numpy as np 
def LU_factorization(A):
    # Input: Matrix A
    # Output: Lower-Triangular Matrix L, and Upper-Triangular Matrix U
    
    n = A.shape[0] # Gets the dimesion of the matrix A
    U = A.copy() # Copy the matrix A into the matrix U
    L = np.identity(n) # Initializes the matrix L
    
    for k in range(n-1): # Loop to iterate every column
        for j in range(k+1,n): # Loop to iterate every row after row k
            L[j,k] = U[j,k]/U[k,k] # Store the value of the multiplier into L
            U[j,k:] = U[j,k:] - L[j,k]*U[k,k:] # Modify the value of U
            
    return [L,U]

<h3 style="color: blue">Operational Count</h3>

The asymptotic operation count of this algorithm can be derived geometrically. The work is dominated by the vector operation in the inner loop $U_{j,k:n} = U_{j,k:n}-L_{j,k}U_{k,k:n}$ which executes one scalar-vector multiplication and one vector subtraction. . If $l = m - k + 1$ denotes the length of the row vectors being manipulated, the number of flops is $2l$: two flops per entry. For each value of $k$, the inner loop is repeated for rows $k+1, \dots , m$. Therefore, the work of LU Factorization is around $\frac{2}{3}n^2$ flops

<h3 style="color:red">Example 1:</h3> 

<strong>Use LU factorization to decompose the matrix $A$ into a lower-triangular matrix $L$ and an upper-triangular matrix $U$</strong>

In [2]:
A = np.matrix('2 1 1 0; 4 3 3 1; 8 7 9 5; 6 7 9 8')
[L,U] = LU_factorization(A)

print("A = ")
print(A)

print("\n L = ")
print(L)

print("\n U = ")
print(U)

# For verification purposes, we can see that if we multiply LU, we will get the matrix A as expected.

print("\n Multiplying LU, we get \n")
print(L.dot(U))

A = 
[[2 1 1 0]
 [4 3 3 1]
 [8 7 9 5]
 [6 7 9 8]]

 L = 
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 3. 1. 0.]
 [3. 4. 1. 1.]]

 U = 
[[2 1 1 0]
 [0 1 1 1]
 [0 0 2 2]
 [0 0 0 2]]

 Multiplying LU, we get 

[[2. 1. 1. 0.]
 [4. 3. 3. 1.]
 [8. 7. 9. 5.]
 [6. 7. 9. 8.]]


<h3 style="color:blue">Solution of Ax = b by LU Factorization</h3>

If $A$ is factored into $L$ and $U$, the system $Ax = b$ is reduced to the form $LUx = b$. Then, we can solve the system by solving two triangular systems: first $Ly = b$ for the unknown $y$ (forward substitution), then $Rx = y$ for the unknown $x$ (back substitution)

In [3]:
def backward_forward_substitution(L,U,b):
    n = b.size
    
    # Backward Substitution
    y = np.zeros(n)
    y[0] = b[0]/L[0,0]
    for l in range(1,n):
        s = 0
        for m in range(0,l):
            s = s + L[l,m]*y[m]
        y[l] = (b[l] - s)/L[l,l]

    # Forward Substitution
    x = np.zeros(n)
    for l in range(n-1,-1,-1):
        t = 0
        for m in range(l+1,n):
            t = t + U[l,m]*x[m]
        x[l] = (y[l] - t)/U[l,l]
    return x.T

<h3 style="color:red">Example 2:</h3> 

<strong>Use LU factorization to decompose the matrix $A$ into a lower-triangular matrix $L$ and an upper-triangular matrix $U$ using the same matrix as example one. Then, solve the system using b = [1, 2, 2, 4]</strong>

In [4]:
# Let's define the vector b
b = np.array([1,2,2,4])

# Since the matrix L and U were already calculated in example 1, 
# we are going to use them in the call of the function backward_forward_substitution
x = backward_forward_substitution(L,U,b)

# The solution vector x is:
print("\n x = ")
print(x)

# Verifyng our solution, we should get that Ax = b
print("\n b = ")
print(A.dot(x))


 x = 
[ 1.25  1.   -2.5   1.5 ]

 b = 
[[1. 2. 2. 4.]]


<h3 style="color:blue">Instability of LU Factorization</h3>

Unfortunately, LU Factorization is unstable for solving general linear systems, since it is not backward stable. The instability is because LU Factorization fails entirely when it attempts division by zero.

<h3 style="color:red">Example 3:</h3> 

<strong>Use LU factorization to decompose the matrix $A$ into a lower-triangular matrix $L$ and an upper-triangular matrix $U$</strong>

In [5]:
A = np.matrix('0 1; 1 1')
print("A = ")
print(A)

[L,U] = LU_factorization(A)
print("\n L = ")
print(L)

print("\n U = ")
print(L)

A = 
[[0 1]
 [1 1]]

 L = 
[[ 1.  0.]
 [inf  1.]]

 U = 
[[ 1.  0.]
 [inf  1.]]


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in long_scalars
  del sys.path[0]
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in multiply
  


We can see that LU Factorization fails at the first step since it tries to have division by zero. Additionally, LU Factorization has problems related to floating point arithmetic.

<h3 style="color:red">Example 4:</h3> 

<strong>Use LU factorization to decompose the matrix $A$ into a lower-triangular matrix $L$ and an upper-triangular matrix $U$</strong>

In [6]:
A = np.matrix([[10**-20,1],[1,1]])
print("A = ")
print(A)

[L,U] = LU_factorization(A)
print("\n L = ")
print(L)

print("\n U = ")
print(L)

#Now calculating LU = A, we get
print("\n LU = ")
print(L.dot(U))

A = 
[[1.e-20 1.e+00]
 [1.e+00 1.e+00]]

 L = 
[[1.e+00 0.e+00]
 [1.e+20 1.e+00]]

 U = 
[[1.e+00 0.e+00]
 [1.e+20 1.e+00]]

 LU = 
[[1.e-20 1.e+00]
 [1.e+00 0.e+00]]


Note that the element $a_{2,2} = 1$ for the matrix $A$, but $a_{2,2}=0$ for the matrix $LU$. 